### ISSUE TITLE
Your understanding of the agpl is flawed.

### ISSUE THREAD

**Issue by vcordie** [BartNixon/Fallout13Beta#1] opened 2017-05-06 06:08 UTC
You must license the entire work, as a whole, under this License to anyone who comes into possession of a copy.

removing the fallout 13 modules before uploading the source is not doing that. Do you take us for fools?

**Comment by BartNixon** [comment] 2017-05-06 13:16
http://www.gnu.org/licenses/agpl-3.0.en.html

> **A separable portion of the object code, whose source code is excluded from the Corresponding Source as a System Library, need not be included in conveying the object code work.**

**Comment by BartNixon** [comment] 2017-05-06 15:34
> **When you convey a copy of a covered work, you may at your option remove any additional permissions from that copy, or from any part of it. (Additional permissions may be written to require their own removal in certain cases when you modify the work.) You may place additional permissions on material, added by you to a covered work, for which you have or can give appropriate copyright permission.**

/tg/ Station 13 has copyright over each and every original /tg/ Station 13 source code asset, though Fallout 13 related code does not belong to original /tg/ Station 13 source code, thus we can give appropriate copyright permissions on our own parts of code and art assets, as we own each and every Fallout 13 related piece, so basically excluding modules and graphics is our legal right.

What you see here on Github is - a Fallout 13 source code, without Fallout 13 related code.
You may, or may not like that, but it actually complies with /tg/ Station 13 AGPL v3 licensing as of January 22 2017 - when the basic code was taken from open-source repo, to make a Fallout 13 on top of it in a complex system of separate modules.

**Comment by BartNixon** [comment] 2017-05-06 15:51
http://www.gnu.org/licenses/agpl-3.0.en.html

> **When you convey a copy of a covered work, you may at your option remove any additional permissions from that copy, or from any part of it. (Additional permissions may be written to require their own removal in certain cases when you modify the work.) You may place additional permissions on material, added by you to a covered work, for which you have or can give appropriate copyright permission.**

/tg/ Station 13 has copyright over each and every original /tg/ Station 13 source code asset (spare the features that were ported from Paradise, inspired or originally created by Goons and other communities), though Fallout 13 related code does not belong to original /tg/ Station 13 source code, thus we can give appropriate copyright permissions on our own parts of code and art assets, as we own each and every Fallout 13 related piece, so basically excluding modules and graphics is our legal right.

What you see here on Github is - a Fallout 13 source code, without Fallout 13 related code.
You may, or may not like that, but it actually complies with /tg/ Station 13 AGPL v3 licensing as of January 22 2017 - when the basic code was taken from open-source repo, to make a Fallout 13 on top of it in a complex system of separate modules.

**Comment by Iamgoofball** [comment] 2017-05-06 16:10
Yeah so can you prove your code runs without relying on our code, commie?

**Comment by BartNixon** [comment] 2017-05-06 16:30
Our code runs relying on /tg/ Station 13 code, we don't deny it.
So we have released exactly the all code, our own code relies on, as /tg/ Station 13 license requires it.

**Comment by Iamgoofball** [comment] 2017-05-06 16:31
You still haven't uploaded your chems that directly use my code.

**Comment by BartNixon** [comment] 2017-05-06 16:38
Fallout 13 Beta doesn't have unique code that you might have provided aside from /tg/ Station 13
If your chems were part of /tg/ Station 13 on January 22 2017 - this repository has it.

I mean, we have released everything that was there, aside from the unique code created by Jackerzz and Godsring, and the art assets voluntarily provided by graphic artists for the project.
If you have contributed your code to a community other than Russian Fallout 13 - we are not responsible for it, you should blame the ones who host it without your explicit permission.
Also you can try, join the Fallout 13 Beta server and actually take a look to make sure we don't have it.
I believe admins may cooperate if you kindly ask them to spawn chem dispenser for you to experiment with, to see if your original feature is used.

**Comment by Iamgoofball** [comment] 2017-05-06 16:40
I want to audit your codebase.

**Comment by maxyo** [comment] 2017-05-06 16:48
Goof, oh Goof...
What's the basis for the audit?
Our specific part of code is a module (mod) for /tg/ Station 13, and is our own property.
Thus we can refuse you an access for an audit - that also doesn't break AGPL terms and conditions.

**Comment by MrStonedOne** [comment] 2017-05-06 17:24
"A separable portion of the object code, whose source code is excluded from the Corresponding Source as a System Library, need not be included in conveying the object code work."

nice try

>The "System Libraries" of an executable work include anything, other
>than the work as a whole, that (a) is included in the normal form of
>packaging a Major Component, but which is not part of that Major
>Component, and (b) serves only to enable use of the work with that
>Major Component, or to implement a Standard Interface for which an
>implementation is available to the public in source code form.  A
>"Major Component", in this context, means a major essential component
>(kernel, window system, and so on) of the specific operating system
>(if any) on which the executable work runs, or a compiler used to
>produce the work, or an object code interpreter used to run it.

**Comment by Iamgoofball** [comment] 2017-05-06 17:29
So I repeat again where the source code @

**Comment by kyrahabattoir** [comment] 2017-05-06 17:31
@MrStonedOne If it works, it works.

**Comment by MrStonedOne** [comment] 2017-05-06 17:32
>When you convey a copy of a covered work, you may at your option remove any additional permissions from that copy, or from any part of it. (Additional permissions may be written to require their own removal in certain cases when you modify the work.) You may place additional permissions on material, added by you to a covered work, for which you have or can give appropriate copyright permission.

So, re-read this one, its pretty careful. it talks about "permissions" not restrictions.

We can give you additional permission to do things the agpl doesn't, and you can add additional permissions yourself, and you can opt to decline the additional permissions, but you can not remove any additional restrictions we added, and you can not add your own restrictions. (later on in the license it allows for adding one restriction, requiring forks mark themselves as using modified code or not use your trademarks)

**Comment by kyrahabattoir** [comment] 2017-05-06 17:34
Doesn't the license contamination only apply to derivative code tho?

**Comment by Iamgoofball** [comment] 2017-05-06 17:40
Their module is a derivative unless it compiles and runs on it's own 100%.

**Comment by kyrahabattoir** [comment] 2017-05-06 17:40
But maybe it does?

**Comment by MrStonedOne** [comment] 2017-05-06 17:42
Notwithstanding any other provision of this License, if you modify the Program, your modified version must prominently offer all users interacting with it remotely through a computer network (if your version supports such interaction) an opportunity to receive the Corresponding Source of your version by providing access to the Corresponding Source from a network server at no charge, through some standard or customary means of facilitating copying of software. This Corresponding Source shall include the Corresponding Source for any work covered by version 3 of the GNU General Public License that is incorporated pursuant to the following paragraph.

To "modify" a work means to copy from or adapt all or part of the work in a fashion requiring copyright permission, other than the making of an exact copy. The resulting work is called a "modified version" of the earlier work or a work "based on" the earlier work.

A "covered work" means either the unmodified Program or a work based on the Program.

**Comment by kyrahabattoir** [comment] 2017-05-06 17:42
I wasn't talking to you @Iamgoofball

**Comment by Iamgoofball** [comment] 2017-05-06 17:44
Eat dicks Kyrah.

**Comment by MrStonedOne** [comment] 2017-05-06 17:44
@kyrahabattoir @BartNixon's own statements prevent it from being seen as seperate:

Our code runs relying on /tg/ Station 13 code, we don't deny it.

If it relies on our code to even compile, its derivative, not transformative.

**Comment by kyrahabattoir** [comment] 2017-05-06 17:47
Yeah but if "our" code is unmodified and their code simply clips over it, there is a definite difference.

Like maps for instance, i'm under no obligation to provide the source of a custom map that I designed for instance.

**Comment by BartNixon** [comment] 2017-05-06 18:50
/tg/ Station 13 owns everything /tg/ Station 13 development team has created for Space Station 13 build.
Everything, that /tg/ Station 13 owns was included to this release, to comply with terms and conditions of a source license.

Fallout 13 community owns everything Fallout 13 community has created for Fallout 13 mod for Space Station 13.
Everything that Fallout 13 community owns, was not included to this release, to comply with terms and conditions of a source license.
We may voluntary upload our modules at any time with ease, because these won't change the core code, but we won't do it for now, as it's our private property we humbly protect - as it was created by our own development team proficient with Byond Game Engine.

By the way, you seem to love this piece of license:
https://www.gnu.org/licenses/gpl-faq.html#GPLModuleLicense

> **The GPL says that the whole combined program has to be released under the GPL. So your module has to be available for use under the GPL.**

You should also remember, that AGPL v3 is an extended version of GPL v3 and it has its own interpretation for certain parts that I have quoted earlier today, thus if you wanted us to comply with the "Modules should be released as well", you should have licensed under common GPL v3, not AGPL v3.
And you should have done it before January 22 2017.

**Comment by MrStonedOne** [comment] 2017-05-06 19:11
that FAQ applies to all 3 gpl licenses, but if you think there is something materially different in regard to modules then why don't you point out what this difference is?

Here, I made it easy for you and generated a diff of the two licenses:

https://github.com/MrStonedOne/diff-engine/pull/1/files

**Comment by BartNixon** [comment] 2017-05-06 19:23
I know why you are doing what you are doing, I don't think there is anyone dumb enough in our dev-team not to understand your reasoning and rights.
I bet you're also intelligent enough to understand our reasoning as well.
Say we voluntarily add original Fallout 13 code modules to this release, would this actually change anything?

**Comment by MrStonedOne** [comment] 2017-05-06 19:32
>Say we voluntarily add original Fallout 13 code modules to this release, would this actually change anything?

If it was all of them, yes

Sprites are another issue, you would need to include enough that it compiles, but it doesn't actually have to be the original sprites. Place holder sprites work, as long as it its enough that the game compiles.

>I bet you're also intelligent enough to understand our reasoning as well.

The issue is your chance to choose to be closed source ended the moment you built your game off our of agpl code.

**Comment by kyrahabattoir** [comment] 2017-05-06 19:35
That's assuming you're right MSO.

**Comment by BartNixon** [comment] 2017-05-06 19:39
It's ok @kyrahabattoir , thanks for the support.
Observe and see what happens next.

**Comment by desertofunknown** [comment] 2017-05-06 20:56
Well if it is true that not all TG developers who contributed to the TG source did not agree to adding the AGPL that would invalidate the AGPL licensing. Given under GPLv3 all developers must give permissions. If someone denied then you removed their code right before changing to AGPL? I suppose further investigation is needed.. it sounds like other coders rights might be violated in this AGPL switch.

**Comment by MrStonedOne** [comment] 2017-05-06 20:59
>Notwithstanding any other provision of this License, you have
>permission to link or combine any covered work with a work licensed
>under version 3 of the GNU Affero General Public License into a single
>combined work, and to convey the resulting work.  The terms of this
>License will continue to apply to the part which is the covered work,
>but the special requirements of the GNU Affero General Public License,
>section 13, concerning interaction through a network will apply to the
>combination as such.

When /tg/ devs made modification to a gpl code base, they consented, under the terms of the license for anybody who ever got ahold of the gpl version, to convert it to agpl.

**Comment by MrStonedOne** [comment] 2017-05-06 21:11
also, Their work (on its own) is still technically licensed under gpl, it's the collection of their work and other work, that /tg/station has, that is AGPL.

This the key point about the gpl and agpl that people don't get, is it see our situation as a collection of work, each contribution owned by the person who coded it, but licensed under the terms, and the collection of that work, as seperate thing, but also licensed under the terms.

Everybody owns their work, but /tg/stations owns the arrangement or collection of works.

The Works may on their own still be gpl if they were made before the gpl move, but the arrangement after that point is agpl, and so is anything (on its own) that was added, since it was based off of agpl arranged code.

**Comment by kyrahabattoir** [comment] 2017-05-06 23:02
@desertofunknown Unfortunately it isn't, the GPLv3 was made by design to have a one way "upgrade" to AGPLv3 through the collection of works section.

My theory is that it was designed as such because while the GPLv2 has a provision to upgrade to GPLv3 (and GPLv3 to a possible future GPLv4), it doesn't allow a move to AGPL without the consent of all developers.

In my case you could say it was due to sheer ignorance as at the time I had never heard of the Affero GPL, naively assumed that v3 was a mere extention of v2 and you can be sure i would never have contributed to a project that uses such a restrictive license.

You can still contribute non-Affero code if you want to anyway but you put yourself in a situation where they can use everything you write, yet you cannot get anything back from them because their license would poison your code.

Which is strikingly similar to the situation they use to explain how closed source doesn't give anything back to open source projects.

**Comment by MrStonedOne** [comment] 2017-05-09 22:53
>You should also remember, that AGPL v3 is an extended version of GPL v3 and it has its own interpretation for certain parts that I have quoted earlier today, thus if you wanted us to comply with the "Modules should be released as well", you should have licensed under common GPL v3, not AGPL v3.
>And you should have done it before January 22 2017.

Here is the FSF on this:

>I believe they are misunderstanding the FAQ. The GPL and AGPL are
largely the same license and what we say about the former applies to the
latter, except when it comes to the particular provision of the AGPL
about network interaction.

**Comment by BartNixon** [comment] 2017-05-17 10:51
![capitulation](https://cloud.githubusercontent.com/assets/9289619/26150587/a9f416b6-3b07-11e7-9925-c241464a6d09.jpg)
**_Fallout 13 development team giving up the futile fight for good_ - circa 2017**

**Comment by BartNixon** [comment] 2017-05-17 10:53
![capitulation2](https://cloud.githubusercontent.com/assets/9289619/26150659/0fcadf38-3b08-11e7-8b80-9b9516bd2c01.jpg)
**_Fallout 13 development team giving up the futile fight for good_ - circa 2017**

**Closed by BartNixon** 2017-05-17 10:53 UTC
